### ISSUE TITLE
贴一下异常日志

### ISSUE THREAD

**Issue by xlmc** [Fansirsqi/Sesame-TK#13]
### 程序版本 / 框架版本 / 模块版本

10.6.63.8000/t24.11.28.alpha/1.9.2（7024）/magisk 28.0stable

### 系统版本 / Android版本

hypeos1.0 android14

### 详细描述问题发生的具体原因

仅蚂蚁森林生效其余不生效

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

00:33:21.842 error: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{d5f48d8 19793:com.eg.android.AlipayGphone/u0a333} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
	at android.os.Parcel.readParcelable(Parcel.java:4852)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7269)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.alipay.stability.workaround.a.f.invoke(SourceFile:52)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy8.setServiceForeground(Unknown Source)
	at android.app.Service.startForeground(Service.java:775)
	at fansirsqi.xposed.sesame.util.NotificationUtil.start(NotificationUtil.java:59)
	at fansirsqi.xposed.sesame.hook.ApplicationHook.initHandler(ApplicationHook.java:586)
	at fansirsqi.xposed.sesame.hook.ApplicationHook.access$400(ApplicationHook.java:42)
	at fansirsqi.xposed.sesame.hook.ApplicationHook$3.afterHookedMethod(ApplicationHook.java:295)
	at Z.tDqocL.YmUU.w.NqmhYN.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.onCreate(Unknown Source:8)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4878)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2410)
	at com.alipay.stability.workaround.a.a.__handleMessage_stub_private(SourceFile:33)
	at com.alipay.stability.workaround.a.a.handleMessage(Unknown Source:49)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8777)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

00:43:29.926 error: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{56b2caa 20832:com.eg.android.AlipayGphone/u0a333} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
	at android.os.Parcel.readParcelable(Parcel.java:4852)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7269)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.alipay.stability.workaround.a.f.invoke(SourceFile:52)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy8.setServiceForeground(Unknown Source)
	at android.app.Service.startForeground(Service.java:775)
	at fansirsqi.xposed.sesame.util.NotificationUtil.start(NotificationUtil.java:59)
	at fansirsqi.xposed.sesame.hook.ApplicationHook.initHandler(ApplicationHook.java:586)
	at fansirsqi.xposed.sesame.hook.ApplicationHook.access$400(ApplicationHook.java:42)
	at fansirsqi.xposed.sesame.hook.ApplicationHook$3.afterHookedMethod(ApplicationHook.java:295)
	at Z.tDqocL.YmUU.w.NqmhYN.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.onCreate(Unknown Source:8)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4878)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2410)
	at com.alipay.stability.workaround.a.a.__handleMessage_stub_private(SourceFile:33)
	at com.alipay.stability.workaround.a.a.handleMessage(Unknown Source:49)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8777)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

00:44:09.618 error: 
=======================================================>
新 RPC 响应 | id: 57499492 | 方法: alipay.antforest.forest.h5.fillUserRobFlag 
参数: [{"userIdList":["2088002234703753","2088912360922765","2088302559867793","2088522767413502","2088812313612340","2088022027841253","2088402176007344","2088622012159404","2088712580059403","2088912975646421"]}] 
数据: {"error":7,"errorMessage":"当前网络不可用，请稍后重试","errorNo":3,"errorTip":"7"}
=======================================================<
00:44:09.622 error: 
=======================================================>
新 RPC 响应 | id: 122883536 | 方法: alipay.antforest.forest.h5.queryPropList 
参数: [{"onlyGive":"","source":"chInfo_ch_appcenter__chsub_9patch","version":"20240403"}] 
数据: {"error":7,"errorMessage":"当前网络不可用，请稍后重试","errorNo":3,"errorTip":"7"}
=======================================================<
00:44:09.622 error: AntForest, org.json.JSONException: No value for resultCode
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getString(JSONObject.java:559)
	at fansirsqi.xposed.sesame.task.antForest.AntForest.getBag(AntForest.java:2605)
	at fansirsqi.xposed.sesame.task.antForest.AntForest.usePropBeforeCollectEnergy(AntForest.java:1887)
	at fansirsqi.xposed.sesame.task.antForest.AntForest.lambda$collectEnergy$1$AntForest(AntForest.java:1087)
	at fansirsqi.xposed.sesame.task.antForest.AntForest$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at fansirsqi.xposed.sesame.task.ModelTask$ChildModelTask.run(ModelTask.java:382)
	at fansirsqi.xposed.sesame.task.SystemChildTaskExecutor.lambda$addChildTask$5(SystemChildTaskExecutor.java:90)
	at fansirsqi.xposed.sesame.task.SystemChildTaskExecutor$$ExternalSyntheticLambda5.run(Unknown Source:2)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

</code></pre></details>

**Comment by Fansirsqi** [comment]
> ### 程序版本 / 框架版本 / 模块版本
> 10.6.63.8000/t24.11.28.alpha/1.9.2（7024）/magisk 28.0stable
> 
> ### 系统版本 / Android版本
> hypeos1.0 android14
> 
> ### 详细描述问题发生的具体原因
> 仅蚂蚁森林生效其余不生效
> 
> ### 提供模块问题 Log 或必要 Log
> 展开查看

检查配置项【只收能量时间(范围)】配置成0000-2359后再试试

**Comment by MobInfinity** [comment]
> > ### 程序版本 / 框架版本 / 模块版本
> > 10.6.63.8000/t24.11.28.alpha/1.9.2（7024）/magisk 28.0stable
> > ### 系统版本 / Android版本
> > hypeos1.0 android14
> > ### 详细描述问题发生的具体原因
> > 仅蚂蚁森林生效其余不生效
> > ### 提供模块问题 Log 或必要 Log
> > 展开查看
> 
> 检查配置项【只收能量时间(范围)】配置成0000-2359后再试试

那不就是全体都只收能量了吗

**Comment by Fansirsqi** [comment]
> > > ### 程序版本 / 框架版本 / 模块版本
> > > 10.6.63.8000/t24.11.28.alpha/1.9.2（7024）/magisk 28.0stable
> > > ### 系统版本 / Android版本
> > > hypeos1.0 android14
> > > ### 详细描述问题发生的具体原因
> > > 仅蚂蚁森林生效其余不生效
> > > ### 提供模块问题 Log 或必要 Log
> > > 展开查看
> > 
> > 
> > 检查配置项【只收能量时间(范围)】配置成0000-2359后再试试
> 
> 那不就是全天都只收能量了吗

对调一下2359-0000
