### ISSUE TITLE
概率弹出已停止工作和蹲点收取感觉异常

### ISSUE THREAD

**Issue by zhangyibin8111** [Fansirsqi/Sesame-TK#31]
### 程序版本 / 框架版本 / 模块版本

程序：10.6.58.9100，LSPosed：1.8.6，模块：24.12.06

### 系统版本 / Android版本

Android 10

### 详细描述问题发生的具体原因

运行时非偷能量时有概率弹出程序已停止工作的弹出，大概是异常日志里面<新 RPC 响应>后弹出的，不知道是哪儿触发的。

还有个问题，不知道是不是只有我这样，早上7点偷能量的时候，前15分钟正常，后面一分钟可能一个都偷不了。我看日志去<执行蹲点收取⏰>去了，然后后面显示的时差也100-1000毫秒不等，差不多同一时间段的时差值都是固定的。设置里面的系统计时、程序计时和平衡网络延迟都调整试过，没效果不知道什么原因

### 提供模块问题 Log 或必要 Log

<details><summary>问题一出现后的异常日志</summary><pre><code>

=======================================================<
07:31:48.137 error: 
=======================================================>
新 RPC 响应 | id: 264444665 | 方法: alipay.kbmemberprod.action.signIn 
参数: [{"sceneCode":"KOUBEI_INTEGRAL","source":"ALIPAY_TAB","version":"2.0"}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<
09:30:42.166 error: java.net.ConnectException: Failed to connect to v1.hitokoto.cn/221.178.98.186:443
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at fansirsqi.xposed.sesame.util.FansirsqiUtil.lambda$getOneWord$0(FansirsqiUtil.java:34)
	at fansirsqi.xposed.sesame.util.FansirsqiUtil$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

10:12:39.695 error: java.net.ConnectException: Failed to connect to v1.hitokoto.cn/221.178.98.182:443
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at fansirsqi.xposed.sesame.util.FansirsqiUtil.lambda$getOneWord$0(FansirsqiUtil.java:34)
	at fansirsqi.xposed.sesame.util.FansirsqiUtil$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

10:13:58.774 error: java.net.ConnectException: Failed to connect to v1.hitokoto.cn/221.178.98.186:443
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at fansirsqi.xposed.sesame.util.FansirsqiUtil.lambda$getOneWord$0(FansirsqiUtil.java:34)
	at fansirsqi.xposed.sesame.util.FansirsqiUtil$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

12:39:20.245 error: java.time.format.DateTimeParseException: Text '-1' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalTime.parse(LocalTime.java:435)
	at fansirsqi.xposed.sesame.util.TimeUtil.getLocalDateTimeByTimeStr(TimeUtil.java:270)
	at fansirsqi.xposed.sesame.hook.ApplicationHook$3$1.run(ApplicationHook.java:276)
	at fansirsqi.xposed.sesame.task.BaseTask$3.run(BaseTask.java:248)
	at fansirsqi.xposed.sesame.task.BaseTask$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:919)

12:39:22.776 error: 
=======================================================>
新 RPC 响应 | id: 232500458 | 方法: alipay.kbmemberprod.action.signIn 
参数: [{"sceneCode":"KOUBEI_INTEGRAL","source":"ALIPAY_TAB","version":"2.0"}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<
12:40:49.387 error: java.time.format.DateTimeParseException: Text '-1' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalTime.parse(LocalTime.java:435)
	at fansirsqi.xposed.sesame.util.TimeUtil.getLocalDateTimeByTimeStr(TimeUtil.java:270)
	at fansirsqi.xposed.sesame.hook.ApplicationHook$3$1.run(ApplicationHook.java:276)
	at fansirsqi.xposed.sesame.task.BaseTask$3.run(BaseTask.java:248)
	at fansirsqi.xposed.sesame.task.BaseTask$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:919)

12:40:51.813 error: 
=======================================================>
新 RPC 响应 | id: 89803001 | 方法: alipay.kbmemberprod.action.signIn 
参数: [{"sceneCode":"KOUBEI_INTEGRAL","source":"ALIPAY_TAB","version":"2.0"}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<
12:44:57.277 error: java.net.ConnectException: Failed to connect to v1.hitokoto.cn/221.178.98.186:443
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at fansirsqi.xposed.sesame.util.FansirsqiUtil.lambda$getOneWord$0(FansirsqiUtil.java:34)
	at fansirsqi.xposed.sesame.util.FansirsqiUtil$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

</code></pre></details>

<details><summary>问题二时间段的部分运行日志，大多数都是这样的</summary><pre><code>

07:22:05.720 runtime: 执行蹲点收取⏰ 任务ID BT|*|1601055945 [*|]时差[1229]ms提前[-500]ms
07:22:05.951 runtime: 收取能量🎈[*|]#1g耗时[231]ms
07:22:05.954 runtime: Files, [statistics]读:true;写:true
07:22:11.723 runtime: 执行蹲点收取⏰ 任务ID BT|*|1606377429 [*|]时差[1229]ms提前[-500]ms
07:22:12.004 runtime: 收取能量🎈[*|]#7g耗时[279]ms
07:22:12.005 runtime: Files, [statistics]读:true;写:true
07:22:28.719 runtime: 执行蹲点收取⏰ 任务ID BT|*|1604473539 [*|]时差[1229]ms提前[-500]ms
07:22:29.004 runtime: 收取能量🎈[*|]#22g耗时[284]ms
07:22:29.007 runtime: Files, [statistics]读:true;写:true
07:22:44.714 runtime: 执行蹲点收取⏰ 任务ID BT|*|1600000672 [*|]时差[1229]ms提前[-500]ms
07:22:44.976 runtime: 收取能量🎈[*|]#15g耗时[262]ms
07:22:44.978 runtime: Files, [statistics]读:true;写:true
07:23:16.711 runtime: 执行蹲点收取⏰ 任务ID BT|*|1600624015 [*|]时差[1229]ms提前[-500]ms
07:23:16.929 runtime: 收取能量🎈[*|]#29g耗时[217]ms
07:23:16.932 runtime: Files, [statistics]读:true;写:true
07:23:25.716 runtime: 执行蹲点收取⏰ 任务ID BT|*|1600506230 [*|]时差[1229]ms提前[-500]ms
07:23:25.989 runtime: [*|]有能量球收取失败了，请重试哟
07:23:25.992 runtime: Files, [statistics]读:true;写:true
07:23:28.712 runtime: 执行蹲点收取⏰ 任务ID BT|*|1603326024 [*|]时差[1229]ms提前[-500]ms
07:23:28.993 runtime: 收取能量🎈[*|]#4g耗时[279]ms
07:23:28.995 runtime: Files, [statistics]读:true;写:true
07:23:29.712 runtime: 执行蹲点收取⏰ 任务ID BT|*|1603128724 [*|]时差[1229]ms提前[-500]ms
07:23:29.975 runtime: 收取能量🎈[*|]#27g耗时[261]ms
07:23:29.976 runtime: Files, [statistics]读:true;写:true

</code></pre></details>

</code></pre></details>

**Comment by zhangyibin8111** [comment]
问题二的森林记录里面有可能几分钟都偷不了一次能量，而且感觉蹲点收取执行速度也很慢，非蹲点的就很正常

**Comment by Fansirsqi** [comment]
请尝试更新版本再试试
