### ISSUE TITLE
支付宝卡死无响应，降级仍存在该问题。

### ISSUE THREAD

**Issue by 045200** [Fansirsqi/Sesame-TK#37]
### 程序版本 / 框架版本 / 模块版本

10.6.70 lsp1.10.1 模块0.2.1

### 系统版本 / Android版本

hyper Android14

### 详细描述问题发生的具体原因

10.6.70/10.6.50/10.6.30/10.6.16都出现打开支付宝后过几秒卡死状态，无法触摸。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>
22:16:43.214 [0.2.1-beta]
=======================================================>
新 RPC 响应 | id: 252935607 | 方法: alipay.antforest.forest.h5.queryPropList 
参数: [{"onlyGive":"Y","source":"chInfo_ch_appcenter__chsub_9patch","version":"20240403"}] 
数据: {"error":7,"errorMessage":"当前网络不可用，请稍后重试","errorNo":3,"errorTip":"7"}
=======================================================<
22:16:43.220 [0.2.1-beta][AntForest]: Throwable error: org.json.JSONException: No value for resultCode
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getString(JSONObject.java:559)
	at fansirsqi.xposed.sesame.task.antForest.AntForest.giveProp(AntForest.java:2127)
	at fansirsqi.xposed.sesame.task.antForest.AntForest.run(AntForest.java:526)
	at fansirsqi.xposed.sesame.task.ModelTask$1.run(ModelTask.java:44)
	at fansirsqi.xposed.sesame.task.ModelTask.startTask(ModelTask.java:216)
	at fansirsqi.xposed.sesame.task.ModelTask.startAllTask(ModelTask.java:261)
	at fansirsqi.xposed.sesame.hook.ApplicationHook$3$1.run(ApplicationHook.java:268)
	at fansirsqi.xposed.sesame.task.BaseTask$3.run(BaseTask.java:248)
	at fansirsqi.xposed.sesame.task.BaseTask$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:1012)

22:23:17.982 [0.2.1-beta]旧 RPC 响应 | id: 114638012 | method: alipay.antforest.forest.h5.giveProp args: [{"giveConfigId":"ANTFOREST_GIVE_ENERGY_DOUBLE_CLICK","propId":"0iw9y191bkdhgh1ae1cmv1qdear68510","source":"self_corner","targetUserId":"2088912941386786"}] | data: {"resultCode":"ROBOT_PUNISHMENT","resultDesc":"您近期操作存在异常，请明天再试","retriable":false,"success":false}
22:23:19.824 [0.2.1-beta]旧 RPC 响应 | id: 215700398 | method: alipay.antforest.forest.h5.giveProp args: [{"giveConfigId":"ANTFOREST_GIVE_ENERGY_DOUBLE_CLICK","propId":"0iw9y191bkdhgh1ae1cmv1qdear68510","source":"self_corner","targetUserId":"2088912941386786"}] | data: {"resultCode":"ROBOT_PUNISHMENT","resultDesc":"您近期操作存在异常，请明天再试","retriable":false,"success":false}
22:23:21.653 [0.2.1-beta]旧 RPC 响应 | id: 60500340 | method: alipay.antforest.forest.h5.giveProp args: [{"giveConfigId":"ANTFOREST_GIVE_ENERGY_DOUBLE_CLICK","propId":"0iw9y191bkdhgh1ae1cmv1qdear68510","source":"self_corner","targetUserId":"2088912941386786"}] | data: {"resultCode":"ROBOT_PUNISHMENT","resultDesc":"您近期操作存在异常，请明天再试","retriable":false,"success":false}
22:23:23.455 [0.2.1-beta]旧 RPC 响应 | id: 171441002 | method: alipay.antforest.forest.h5.giveProp args: [{"giveConfigId":"ANTFOREST_GIVE_ENERGY_DOUBLE_CLICK","propId":"0iw9y191bkdhgh1ae1cmv1qdear68510","source":"self_corner","targetUserId":"2088912941386786"}] | data: {"resultCode":"ROBOT_PUNISHMENT","resultDesc":"您近期操作存在异常，请明天再试","retriable":false,"success":false}
22:23:25.377 [0.2.1-beta]旧 RPC 响应 | id: 26231168 | method: alipay.antforest.forest.h5.giveProp args: [{"giveConfigId":"ANTFOREST_GIVE_ENERGY_DOUBLE_CLICK","propId":"0iw9y191bkdhgh1ae1cmv1qdear68510","source":"self_corner","targetUserId":"2088912941386786"}] | data: {"resultCode":"ROBOT_PUNISHMENT","resultDesc":"您近期操作存在异常，请明天再试","retriable":false,"success":false}
22:25:12.902 [0.2.1-beta]旧 RPC 响应 | id: 40018398 | method: alipay.antforest.forest.h5.giveProp args: [{"giveConfigId":"ANTFOREST_GIVE_ENERGY_DOUBLE_CLICK","propId":"0iw9y191bkdhgh1ae1cmv1qdear68510","source":"self_corner","targetUserId":"2088912941386786"}] | data: {"resultCode":"ROBOT_PUNISHMENT","resultDesc":"您近期操作存在异常，请明天再试","retriable":false,"success":false}
22:25:14.687 [0.2.1-beta]旧 RPC 响应 | id: 70617674 | method: alipay.antforest.forest.h5.giveProp args: [{"giveConfigId":"ANTFOREST_GIVE_ENERGY_DOUBLE_CLICK","propId":"0iw9y191bkdhgh1ae1cmv1qdear68510","source":"self_corner","targetUserId":"2088912941386786"}] | data: {"resultCode":"ROBOT_PUNISHMENT","resultDesc":"您近期操作存在异常，请明天再试","retriable":false,"success":false}
22:25:16.431 [0.2.1-beta]旧 RPC 响应 | id: 193924081 | method: alipay.antforest.forest.h5.giveProp args: [{"giveConfigId":"ANTFOREST_GIVE_ENERGY_DOUBLE_CLICK","propId":"0iw9y191bkdhgh1ae1cmv1qdear68510","source":"self_corner","targetUserId":"2088912941386786"}] | data: {"resultCode":"ROBOT_PUNISHMENT","resultDesc":"您近期操作存在异常，请明天再试","retriable":false,"success":false}
22:25:18.312 [0.2.1-beta]旧 RPC 响应 | id: 178662618 | method: alipay.antforest.forest.h5.giveProp args: [{"giveConfigId":"ANTFOREST_GIVE_ENERGY_DOUBLE_CLICK","propId":"0iw9y191bkdhgh1ae1cmv1qdear68510","source":"self_corner","targetUserId":"2088912941386786"}] | data: {"resultCode":"ROBOT_PUNISHMENT","resultDesc":"您近期操作存在异常，请明天再试","retriable":false,"success":false}

(此处粘贴问题 Log)

</code></pre></details>

**Comment by luzilong520** [comment]
更新了一样还是这个问题，不知道是怎么个回事

**Comment by luzilong520** [comment]
08:15:41.181 [0.2.0-alpha.fix]error: java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:807)
	at java.lang.Integer.parseInt(Integer.java:915)
	at fansirsqi.xposed.sesame.model.modelFieldExt.IntegerModelField.setConfigValue(IntegerModelField.java:93)
	at fansirsqi.xposed.sesame.model.modelFieldExt.IntegerModelField$MultiplyIntegerModelField.setConfigValue(IntegerModelField.java:191)
	at fansirsqi.xposed.sesame.ui.NewSettingsActivity$WebViewCallback.setModel(NewSettingsActivity.java:244)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:341)
	at android.os.Looper.loopOnce(Looper.java:176)
	at android.os.Looper.loop(Looper.java:318)
	at android.os.HandlerThread.run(HandlerThread.java:67)

08:16:36.274 [0.2.0-alpha.fix]error: java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:807)
	at java.lang.Integer.parseInt(Integer.java:915)
	at fansirsqi.xposed.sesame.model.modelFieldExt.IntegerModelField.setConfigValue(IntegerModelField.java:93)
	at fansirsqi.xposed.sesame.model.modelFieldExt.IntegerModelField$MultiplyIntegerModelField.setConfigValue(IntegerModelField.java:191)
	at fansirsqi.xposed.sesame.ui.NewSettingsActivity$WebViewCallback.setModel(NewSettingsActivity.java:244)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:341)
	at android.os.Looper.loopOnce(Looper.java:176)
	at android.os.Looper.loop(Looper.java:318)
	at android.os.HandlerThread.run(HandlerThread.java:67)

08:16:45.615 [0.2.0-alpha.fix]error: java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:807)
	at java.lang.Integer.parseInt(Integer.java:915)
	at fansirsqi.xposed.sesame.model.modelFieldExt.IntegerModelField.setConfigValue(IntegerModelField.java:93)
	at fansirsqi.xposed.sesame.model.modelFieldExt.IntegerModelField$MultiplyIntegerModelField.setConfigValue(IntegerModelField.java:191)
	at fansirsqi.xposed.sesame.ui.NewSettingsActivity$WebViewCallback.setModel(NewSettingsActivity.java:244)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:341)
	at android.os.Looper.loopOnce(Looper.java:176)
	at android.os.Looper.loop(Looper.java:318)
	at android.os.HandlerThread.run(HandlerThread.java:67)

09:40:44.968 [0.2.0-alpha.fix][AntSports]: error: java.lang.NumberFormatException: For input string: "2024-12-13 09"
	at java.lang.Integer.parseInt(Integer.java:797)
	at java.lang.Integer.parseInt(Integer.java:915)
	at fansirsqi.xposed.sesame.task.antSports.AntSports.queryWalkStep(AntSports.java:722)
	at fansirsqi.xposed.sesame.task.antSports.AntSports.run(AntSports.java:147)
	at fansirsqi.xposed.sesame.task.ModelTask$1.run(ModelTask.java:44)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

09:40:50.217 [0.2.0-alpha.fix]
=======================================================>
新 RPC 响应 | id: 265946853 | 方法: alipay.kbmemberprod.action.signIn 
参数: [{"sceneCode":"KOUBEI_INTEGRAL","source":"ALIPAY_TAB","version":"2.0"}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<
09:40:51.583 [0.2.0-alpha.fix]
=======================================================>
新 RPC 响应 | id: 184932177 | 方法: alipay.antsports.club.train.trainMember 
参数: [{"chInfo":"healthstep","itemType":"barbell","memberId":"cm0000002088132811982344","originBossId":"2088132811982344"}] 
数据: {"error":7,"errorMessage":"当前网络不可用，请稍后重试","errorNo":3,"errorTip":"7"}
=======================================================<
09:40:51.593 [0.2.0-alpha.fix]
=======================================================>
新 RPC 响应 | id: 111734026 | 方法: alipay.mrchservbase.mrchbusiness.sign.transcode.check 
参数: [{}] 
数据: {"error":7,"errorMessage":"当前网络不可用，请稍后重试","errorNo":3,"errorTip":"7"}
=======================================================<
11:21:30.903 [0.2.0-alpha.fix][AntForest]: error: org.json.JSONException: No value for studentCheckInInfo
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONObject(JSONObject.java:618)
	at fansirsqi.xposed.sesame.task.antForest.AntForest.studentTaskHandle(AntForest.java:696)
	at fansirsqi.xposed.sesame.task.antForest.AntForest.studentSignInRedEnvelope(AntForest.java:661)
	at fansirsqi.xposed.sesame.task.antForest.AntForest.run(AntForest.java:564)
	at fansirsqi.xposed.sesame.task.ModelTask$1.run(ModelTask.java:44)
	at fansirsqi.xposed.sesame.task.ModelTask.startTask(ModelTask.java:216)
	at fansirsqi.xposed.sesame.task.ModelTask.startAllTask(ModelTask.java:261)
	at fansirsqi.xposed.sesame.hook.ApplicationHook$3$1.run(ApplicationHook.java:268)
	at fansirsqi.xposed.sesame.task.BaseTask$3.run(BaseTask.java:24

**Comment by Fansirsqi** [comment]
> 08:15:41.181 [0.2.0-alpha.fix]error: java.lang.NumberFormatException: For input string: "" at java.lang.Integer.parseInt(Integer.java:807) at java.lang.Integer.parseInt(Integer.java:915) at fansirsqi.xposed.sesame.model.modelFieldExt.IntegerModelField.setConfigValue(IntegerModelField.java:93) at fansirsqi.xposed.sesame.model.modelFieldExt.IntegerModelField$MultiplyIntegerModelField.setConfigValue(IntegerModelField.java:191) at fansirsqi.xposed.sesame.ui.NewSettingsActivity$WebViewCallback.setModel(NewSettingsActivity.java:244) at android.os.MessageQueue.nativePollOnce(Native Method) at android.os.MessageQueue.next(MessageQueue.java:341) at android.os.Looper.loopOnce(Looper.java:176) at android.os.Looper.loop(Looper.java:318) at android.os.HandlerThread.run(HandlerThread.java:67)
> 
> 08:16:36.274 [0.2.0-alpha.fix]error: java.lang.NumberFormatException: For input string: "" at java.lang.Integer.parseInt(Integer.java:807) at java.lang.Integer.parseInt(Integer.java:915) at fansirsqi.xposed.sesame.model.modelFieldExt.IntegerModelField.setConfigValue(IntegerModelField.java:93) at fansirsqi.xposed.sesame.model.modelFieldExt.IntegerModelField$MultiplyIntegerModelField.setConfigValue(IntegerModelField.java:191) at fansirsqi.xposed.sesame.ui.NewSettingsActivity$WebViewCallback.setModel(NewSettingsActivity.java:244) at android.os.MessageQueue.nativePollOnce(Native Method) at android.os.MessageQueue.next(MessageQueue.java:341) at android.os.Looper.loopOnce(Looper.java:176) at android.os.Looper.loop(Looper.java:318) at android.os.HandlerThread.run(HandlerThread.java:67)
> 
> 08:16:45.615 [0.2.0-alpha.fix]error: java.lang.NumberFormatException: For input string: "" at java.lang.Integer.parseInt(Integer.java:807) at java.lang.Integer.parseInt(Integer.java:915) at fansirsqi.xposed.sesame.model.modelFieldExt.IntegerModelField.setConfigValue(IntegerModelField.java:93) at fansirsqi.xposed.sesame.model.modelFieldExt.IntegerModelField$MultiplyIntegerModelField.setConfigValue(IntegerModelField.java:191) at fansirsqi.xposed.sesame.ui.NewSettingsActivity$WebViewCallback.setModel(NewSettingsActivity.java:244) at android.os.MessageQueue.nativePollOnce(Native Method) at android.os.MessageQueue.next(MessageQueue.java:341) at android.os.Looper.loopOnce(Looper.java:176) at android.os.Looper.loop(Looper.java:318) at android.os.HandlerThread.run(HandlerThread.java:67)
> 
> 09:40:44.968 [0.2.0-alpha.fix][AntSports]: error: java.lang.NumberFormatException: For input string: "2024-12-13 09" at java.lang.Integer.parseInt(Integer.java:797) at java.lang.Integer.parseInt(Integer.java:915) at fansirsqi.xposed.sesame.task.antSports.AntSports.queryWalkStep(AntSports.java:722) at fansirsqi.xposed.sesame.task.antSports.AntSports.run(AntSports.java:147) at fansirsqi.xposed.sesame.task.ModelTask$1.run(ModelTask.java:44) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) at java.lang.Thread.run(Thread.java:1012)
> 
> 09:40:50.217 [0.2.0-alpha.fix] =======================================================> 新 RPC 响应 | id: 265946853 | 方法: alipay.kbmemberprod.action.signIn 参数: [{"sceneCode":"KOUBEI_INTEGRAL","source":"ALIPAY_TAB","version":"2.0"}] 数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"} =======================================================< 09:40:51.583 [0.2.0-alpha.fix] =======================================================> 新 RPC 响应 | id: 184932177 | 方法: alipay.antsports.club.train.trainMember 参数: [{"chInfo":"healthstep","itemType":"barbell","memberId":"cm0000002088132811982344","originBossId":"2088132811982344"}] 数据: {"error":7,"errorMessage":"当前网络不可用，请稍后重试","errorNo":3,"errorTip":"7"} =======================================================< 09:40:51.593 [0.2.0-alpha.fix] =======================================================> 新 RPC 响应 | id: 111734026 | 方法: alipay.mrchservbase.mrchbusiness.sign.transcode.check 参数: [{}] 数据: {"error":7,"errorMessage":"当前网络不可用，请稍后重试","errorNo":3,"errorTip":"7"} =======================================================< 11:21:30.903 [0.2.0-alpha.fix][AntForest]: error: org.json.JSONException: No value for studentCheckInInfo at org.json.JSONObject.get(JSONObject.java:398) at org.json.JSONObject.getJSONObject(JSONObject.java:618) at fansirsqi.xposed.sesame.task.antForest.AntForest.studentTaskHandle(AntForest.java:696) at fansirsqi.xposed.sesame.task.antForest.AntForest.studentSignInRedEnvelope(AntForest.java:661) at fansirsqi.xposed.sesame.task.antForest.AntForest.run(AntForest.java:564) at fansirsqi.xposed.sesame.task.ModelTask$1.run(ModelTask.java:44) at fansirsqi.xposed.sesame.task.ModelTask.startTask(ModelTask.java:216) at fansirsqi.xposed.sesame.task.ModelTask.startAllTask(ModelTask.java:261) at fansirsqi.xposed.sesame.hook.ApplicationHook$3$1.run(ApplicationHook.java:268) at fansirsqi.xposed.sesame.task.BaseTask$3.run(BaseTask.java:24

请尝试更新到latest版本再次反馈，十分感谢您的反馈

**Comment by luzilong520** [comment]
00:01:56.050 [0.2.1-beta]
=======================================================>
新 RPC 响应 | id: 242863751 | 方法: com.alipay.adexchange.ad.facade.xlightPlugin 
参数: [{"positionRequest":{"extMap":{"xlightPlayInstanceId":"300004"},"referInfo":{},"spaceCode":"ANT_FARM_NEW_VILLAGE"},"sdkPageInfo":{"adComponentType":"FEEDS","adComponentVersion":"4.11.13","enableFusion":true,"networkType":"WIFI","pageFrom":"ch_url-https://68687809.h5app.alipay.com/www/game.html","pageNo":1,"pageUrl":"https://render.alipay.com/p/yuyan/180020010001256918/multi-stage-task.html?caprMode=sync&spaceCodeFeeds=ANT_FARM_NEW_VILLAGE&usePlayLink=true&xlightPlayInstanceId=300004","session":"u_54b721d9fffd6_1904b8eba8f","unionAppId":"2060090000304921","usePlayLink":"true","xlightSDKType":"h5","xlightSDKVersion":"4.11.13"}}] 
数据: {"adList":[],"ariverRpcTraceId":"2199e98e17341057161505271e3076","enableNewPlayingProto":true,"errorMsg":"this is a cheating traffic","extInfo":{},"pagingParam":{"hasNext":true,"pageNo":1,"pageSize":20,"session":"u_54b721d9fffd6_1904b8eba8f"},"playingResult":{"eventRewardDetail":{"browsingStepType":1,"eventHandleType":1,"eventRewardInfoList":[{"endOrder":0,"eventStep":15,"eventStepType":"duration","hasLoopEvent":false,"maxLoopCount":0,"noticeMediaFinish":false,"order":0,"playingEventType":"BROWSE","rewardId":40700005,"rewardNumber":3,"rewardRenderInfo":{"rewardDisplayAmount":"3","rewardDisplayText":"产速","rewardIcon":"https://mdn.alipayobjects.com/huamei_ouecfj/afts/img/A*7_dJRY75kvoAAAAAAAAAAAAADsqsAQ/original","rewardUnitDisplayText":"/时"}},{"endOrder":0,"eventStep":15,"eventStepType":"duration","hasLoopEvent":false,"maxLoopCount":0,"noticeMediaFinish":false,"order":1,"playingEventType":"BROWSE","rewardId":40700005,"rewardNumber":3,"rewardRenderInfo":{"rewardDisplayAmount":"3","rewardDisplayText":"产速","rewardIcon":"https://mdn.alipayobjects.com/huamei_ouecfj/afts/img/A*7_dJRY75kvoAAAAAAAAAAAAADsqsAQ/original","rewardUnitDisplayText":"/时"}}]},"playingBizId":"cc07d068c1ad9c47ee3fee31e127a8b5","playingBizStatus":0,"playingRenderSchema":{"floatPicture":{"defaultValue":"https://mdn.alipayobjects.com/huamei_ouecfj/afts/img/A*c-ztRoAOZHsAAAAAAAAAAAAADsqsAQ/original"},"float_text":{"defaultValue":"滑动浏览15s得奖励","error":"网络异常","finished":"任务已完成"},"rewardArrows":{"defaultValue":"https://mdn.alipayobjects.com/huamei_ouecfj/afts/img/A*0nBrTZ_WKs4AAAAAAAAAAAAADsqsAQ/original"},"rewardFrameTitle":{"defaultValue":"每浏览15秒可得1次奖励","sliding":""},"rewardFrameWordColor":{"defaultValue":"#6b421d"},"rewardPrefix":{"defaultValue":"+"},"topPicture":{"defaultValue":"https://mdn.alipayobjects.com/huamei_ouecfj/afts/img/A*zOV0SL8Mr5gAAAAAAAAAAAAADsqsAQ/original","sliding":"https://mdn.alipayobjects.com/huamei_ouecfj/afts/img/A*GZ_RR4lCqaQAAAAAAAAAAAAADsqsAQ/original"},"topSubTitle":{"defaultValue":"滑动浏览或查看商品得奖励","sliding":""},"topTitle":{"defaultValue":"浏览得奖励","finished":"滑动浏览或查看商品"}},"playingStyleType":"BIZDOMAIN_COMMON_BROWSING_FEEDS","playingType":"BROWSING"},"retCode":"217","sspErrorCode":"61002","sspErrorMsg":"广告请求错误","xlightRequestId":"318064f93ff04746a60c71f80c9d9bf1"}
=======================================================<
00:02:01.499 [0.2.1-beta]
=======================================================>
新 RPC 响应 | id: 233393409 | 方法: alipay.kbmemberprod.action.signIn 
参数: [{"sceneCode":"KOUBEI_INTEGRAL","source":"ALIPAY_TAB","version":"2.0"}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<
00:02:03.244 [0.2.1-beta]
=======================================================>
新 RPC 响应 | id: 202089254 | 方法: alipay.mrchservbase.zcj.taskList.query 
参数: [{"compId":"ZCJ_TASK_LIST","params":{"activityCode":"ZCJ","clientVersion":"10.3.36","extInfo":{},"platform":"Android","underTakeTaskCode":""}}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<

**Comment by Fansirsqi** [comment]
把插件降到t11.29那个版本会有这种情况吗

**Comment by luzilong520** [comment]
> 把插件降到t11.29那个版本会有这种情况吗

一直以来都有这个问题，直到有人发帖出来我才跟着反馈，只要把森林关了，就不会进去支付宝会卡死，无响应

**Comment by luzilong520** [comment]
08:57:04.980 [0.2.2-alpha]
=======================================================>
新 RPC 响应 | id: 218197233 | 方法: alipay.kbmemberprod.action.signIn 
参数: [{"sceneCode":"KOUBEI_INTEGRAL","source":"ALIPAY_TAB","version":"2.0"}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<
10:45:28.344 [0.2.2-alpha]
=======================================================>
新 RPC 响应 | id: 19541415 | 方法: alipay.kbmemberprod.action.signIn 
参数: [{"sceneCode":"KOUBEI_INTEGRAL","source":"ALIPAY_TAB","version":"2.0"}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<
10:45:30.133 [0.2.2-alpha]
=======================================================>
新 RPC 响应 | id: 120375123 | 方法: alipay.mrchservbase.zcj.taskList.query 
参数: [{"compId":"ZCJ_TASK_LIST","params":{"activityCode":"ZCJ","clientVersion":"10.3.36","extInfo":{},"platform":"Android","underTakeTaskCode":""}}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<
11:37:37.567 [0.2.2-alpha]
=======================================================>
新 RPC 响应 | id: 1855050 | 方法: alipay.kbmemberprod.action.signIn 
参数: [{"sceneCode":"KOUBEI_INTEGRAL","source":"ALIPAY_TAB","version":"2.0"}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<
11:37:40.397 [0.2.2-alpha]
=======================================================>
新 RPC 响应 | id: 12111052 | 方法: alipay.mrchservbase.zcj.taskList.query 
参数: [{"compId":"ZCJ_TASK_LIST","params":{"activityCode":"ZCJ","clientVersion":"10.3.36","extInfo":{},"platform":"Android","underTakeTaskCode":""}}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<
11:43:17.496 [0.2.2-alpha]
=======================================================>
新 RPC 响应 | id: 115367388 | 方法: alipay.kbmemberprod.action.signIn 
参数: [{"sceneCode":"KOUBEI_INTEGRAL","source":"ALIPAY_TAB","version":"2.0"}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<
11:43:19.704 [0.2.2-alpha]
=======================================================>
新 RPC 响应 | id: 230070082 | 方法: alipay.mrchservbase.zcj.taskList.query 
参数: [{"compId":"ZCJ_TASK_LIST","params":{"activityCode":"ZCJ","clientVersion":"10.3.36","extInfo":{},"platform":"Android","underTakeTaskCode":""}}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<
12:39:51.944 [0.2.2-alpha]
=======================================================>
新 RPC 响应 | id: 240611644 | 方法: alipay.kbmemberprod.action.signIn 
参数: [{"sceneCode":"KOUBEI_INTEGRAL","source":"ALIPAY_TAB","version":"2.0"}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<
12:39:55.542 [0.2.2-alpha]
=======================================================>
新 RPC 响应 | id: 217943558 | 方法: alipay.mrchservbase.zcj.taskList.query 
参数: [{"compId":"ZCJ_TASK_LIST","params":{"activityCode":"ZCJ","clientVersion":"10.3.36","extInfo":{},"platform":"Android","underTakeTaskCode":""}}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<
15:08:52.668 [0.2.2-alpha]
=======================================================>
新 RPC 响应 | id: 162752090 | 方法: alipay.kbmemberprod.action.signIn 
参数: [{"sceneCode":"KOUBEI_INTEGRAL","source":"ALIPAY_TAB","version":"2.0"}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}最新版还是无响应，关了森林就正常了

**Comment by acooler15** [comment]
请求响应异常了，是不是请求间隔太小了？
