### ISSUE TITLE
0.2.2-0.2.1内置都会无响应

### ISSUE THREAD

**Issue by xiaoke799** [Fansirsqi/Sesame-TK#40]
### 程序版本 / 框架版本 / 模块版本

支付宝版本10.6.66.8000和10.6.70.8100框架版本LSPATCH0.6,zpatch0.6.7

### 系统版本 / Android版本

Android 14

### 详细描述问题发生的具体原因

内置过后打开能成功加载，但是加载完一分钟支付宝就卡死 无响应

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(21:10:41.291 [0.2.2-alpha]
=======================================================>
新 RPC 响应 | id: 147821882 | 方法: alipay.antforest.forest.h5.fillUserRobFlag 
参数: [{"userIdList":["2088522564688710","2088802564171604","2088012962560539","2088712775238505","2088312518583264","2088902886026890","2088622871180201","2088822158349262","2088532012001411","2088832362295244","2088522181682962","2088212887589451","2088612281881333","2088532001051829","2088022442146605","2088022756935494","2088332290500680","2088502194829684","2088512083075379","2088532639223090"]}] 
数据: {"error":7,"errorMessage":"当前网络不可用，请稍后重试","errorNo":3,"errorTip":"7"}
=======================================================<
21:11:37.034 [0.2.2-alpha]
=======================================================>
新 RPC 响应 | id: 209996604 | 方法: alipay.kbmemberprod.action.signIn 
参数: [{"sceneCode":"KOUBEI_INTEGRAL","source":"ALIPAY_TAB","version":"2.0"}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<
21:11:39.531 [0.2.2-alpha]
=======================================================>
新 RPC 响应 | id: 100490714 | 方法: alipay.mrchservbase.zcj.taskList.query 
参数: [{"compId":"ZCJ_TASK_LIST","params":{"activityCode":"ZCJ","clientVersion":"10.3.36","extInfo":{},"platform":"Android","underTakeTaskCode":""}}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<
21:13:25.345 [0.2.2-alpha]error: de.robv.android.xposed.XposedHelpers$InvocationTargetError: java.lang.VerifyError: Verifier rejected class com.alipay.mobile.socialcommonsdk.bizdata.contact.data.AliAccountDaoOp: void com.alipay.mobile.socialcommonsdk.bizdata.contact.data.AliAccountDaoOp.createOrUpdateAccountInfoForSync(int, com.alipay.mobile.socialcommonsdk.bizdata.contact.model.SyncContactModel, com.alipay.mobile.personalbase.service.PinyinSearchService) failed to verify: void com.alipay.mobile.socialcommonsdk.bizdata.contact.data.AliAccountDaoOp.createOrUpdateAccountInfoForSync(int, com.alipay.mobile.socialcommonsdk.bizdata.contact.model.SyncContactModel, com.alipay.mobile.personalbase.service.PinyinSearchService): [0x5F] cannot access instance field java.lang.String com.alipay.mobilerelation.common.service.facade.result.FriendVO.userId from object of type Unresolved Reference: com.alipay.mobile.socialcommonsdk.bizdata.contact.model.FriendVoExtendModel (declaration of 'com.alipay.mobile.socialcommonsdk.bizdata.contact.data.AliAccountDaoOp' appears in /data/user/0/com.eg.android.AlipayGphone/cache/lspatch/origin/4147032220.apk!classes12.dex)
	at de.robv.android.xposed.XposedHelpers.callStaticMethod(XposedHelpers.java:1507)
	at fansirsqi.xposed.sesame.util.Maps.UserMap.lambda$initUser$0(UserMap.java:89)
	at fansirsqi.xposed.sesame.util.Maps.UserMap$$ExternalSyntheticLambda0.run(Unknown Source:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8777)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.VerifyError: Verifier rejected class com.alipay.mobile.socialcommonsdk.bizdata.contact.data.AliAccountDaoOp: void com.alipay.mobile.socialcommonsdk.bizdata.contact.data.AliAccountDaoOp.createOrUpdateAccountInfoForSync(int, com.alipay.mobile.socialcommonsdk.bizdata.contact.model.SyncContactModel, com.alipay.mobile.personalbase.service.PinyinSearchService) failed to verify: void com.alipay.mobile.socialcommonsdk.bizdata.contact.data.AliAccountDaoOp.createOrUpdateAccountInfoForSync(int, com.alipay.mobile.socialcommonsdk.bizdata.contact.model.SyncContactModel, com.alipay.mobile.personalbase.service.PinyinSearchService): [0x5F] cannot access instance field java.lang.String com.alipay.mobilerelation.common.service.facade.result.FriendVO.userId from object of type Unresolved Reference: com.alipay.mobile.socialcommonsdk.bizdata.contact.model.FriendVoExtendModel (declaration of 'com.alipay.mobile.socialcommonsdk.bizdata.contact.data.AliAccountDaoOp' appears in /data/user/0/com.eg.android.AlipayGphone/cache/lspatch/origin/4147032220.apk!classes12.dex)

21:15:20.808 [0.2.2-alpha]
=======================================================>
新 RPC 响应 | id: 100745507 | 方法: alipay.kbmemberprod.action.signIn 
参数: [{"sceneCode":"KOUBEI_INTEGRAL","source":"ALIPAY_TAB","version":"2.0"}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<
21:15:23.507 [0.2.2-alpha]
=======================================================>
新 RPC 响应 | id: 192233663 | 方法: alipay.mrchservbase.zcj.taskList.query 
参数: [{"compId":"ZCJ_TASK_LIST","params":{"activityCode":"ZCJ","clientVersion":"10.3.36","extInfo":{},"platform":"Android","underTakeTaskCode":""}}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<)

</code></pre></details>

**Comment by xiaoke799** [comment]
目前使用24.11.29.alpha.18.31.52版本无卡顿

**Comment by acooler15** [comment]
程序并没有直接反射调用`com.alipay.mobile.socialcommonsdk.bizdata.contact.model.FriendVoExtendModel`、`com.alipay.mobilerelation.common.service.facade.result.FriendVO`，这两个类是`com.alipay.mobile.socialcommonsdk.bizdata.contact.data.AliAccountDaoOp`调用的。在支付宝中，`FriendVoExtendModel`类是继承于`FriendVO`类的，不应该出现找不到`userId`的情况啊，是否是安装包制作或制作的安装包安装时的问题？

**Comment by Fansirsqi** [comment]
@acooler15 从错误日志中可以看出，这个问题是由 `java.lang.VerifyError` 引起的，主要原因是字节码验证器拒绝了某个类（`AliAccountDaoOp`）。问题的根本可能与以下几个方面有关：

---

### 1. 不兼容的字节码/DEX 文件结构
   - 原因**：目标类的字节码可能与当前运行时环境不兼容。例如，可能是不同的编译器版本、修改过的 DEX 文件，或者打补丁时的工具（如 LsPatch）生成了无效的字节码。
   - **日志中的线索**：
     ```
     declaration of 'com.alipay.mobile.socialcommonsdk.bizdata.contact.data.AliAccountDaoOp' appears in /data/user/0/com.eg.android.AlipayGphone/cache/lspatch/origin/4147032220.apk!classes12.dex
     ```
     - 指向 `classes12.dex`，说明这个类来源于分包的 Dex 文件。使用动态加载的 Dex 文件可能与环境不匹配，导致验证失败。

---

### **2. 访问了不受支持的字段或类型
   - 原因**：某些字段或类型在运行时未正确加载或已被混淆/修改。根据日志：
     ```
     cannot access instance field java.lang.String com.alipay.mobilerelation.common.service.facade.result.FriendVO.userId
     ```
     - `FriendVO.userId` 字段无法访问，表明 `FriendVO` 或其子类 `FriendVoExtendModel` 在当前 Dex 环境中未正确解析。
   - **可能场景**：
     1. **类型定义问题**：`FriendVO` 或 `FriendVoExtendModel` 的字节码与运行时版本不一致。
     2. **动态加载问题**：目标类型未包含在加载的 Dex 文件中，或者加载失败。

---

### **3. 动态 Hook 或字节码操作不当
   - 原因**：Xposed 框架的 Hook 或修改可能导致字节码结构被破坏。
   - **日志中的线索**：
     ```
     at de.robv.android.xposed.XposedHelpers.callStaticMethod
     ```
     - Xposed 框架尝试调用目标方法时，由于字节码验证失败而抛出异常。
   - **潜在问题**：
     1. 目标方法签名 `createOrUpdateAccountInfoForSync` 被混淆或修改，导致参数或返回值类型不匹配。
     2. Hook 的类或方法已被安全机制（如支付宝防护）检测并动态替换或加密。

---

### **4. 运行环境问题
   - 原因**：Android 的 ART 或 Dalvik 虚拟机在特定版本上可能存在不兼容问题。
   - **可能场景**：
     - 目标 Dex 文件中的字段或方法超出了 VM 的限制（如方法数限制）。
     - 目标环境使用了 ART 特性，但 Dex 文件是针对 Dalvik 编译的，或者反之。

---

### **解决方案
#### 1. 检查目标类及其依赖
   - 确保 AliAccountDaoOp 及相关类（如 FriendVO 和 `FriendVoExtendModel`）在目标 Dex 文件中正确定义。
   - 通过反编译工具（如 JADX、Baksmali）检查目标 Dex 文件，验证 `createOrUpdateAccountInfoForSync` 的签名是否与代码一致。

#### 2. 校验加载的 Dex 文件
   - 确保加载的 classes12.dex 未损坏或被混淆。
   - 如果使用了补丁工具（如 LsPatch），尝试重新生成补丁。

**Comment by xiaoke799** [comment]
用ZPATCH内之后能成功运行，但是运行过后支付宝会无响应，模块端有日志输出，支付宝无法点击，但是模块执行结束后支付宝又能正常操作

**Comment by xiaoke799** [comment]
10:51:06.596 [0.2.2-alpha]
=======================================================>
新 RPC 响应 | id: 121793873 | 方法: alipay.kbmemberprod.action.signIn 
参数: [{"sceneCode":"KOUBEI_INTEGRAL","source":"ALIPAY_TAB","version":"2.0"}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<
10:51:10.349 [0.2.2-alpha]
=======================================================>
新 RPC 响应 | id: 133458888 | 方法: alipay.mrchservbase.zcj.taskList.query 
参数: [{"compId":"ZCJ_TASK_LIST","params":{"activityCode":"ZCJ","clientVersion":"10.3.36","extInfo":{},"platform":"Android","underTakeTaskCode":""}}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<
10:52:39.942 [0.2.2-alpha]
=======================================================>
新 RPC 响应 | id: 88178735 | 方法: alipay.kbmemberprod.action.signIn 
参数: [{"sceneCode":"KOUBEI_INTEGRAL","source":"ALIPAY_TAB","version":"2.0"}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<
10:52:42.556 [0.2.2-alpha]
=======================================================>
新 RPC 响应 | id: 105430771 | 方法: alipay.mrchservbase.zcj.taskList.query 
参数: [{"compId":"ZCJ_TASK_LIST","params":{"activityCode":"ZCJ","clientVersion":"10.3.36","extInfo":{},"platform":"Android","underTakeTaskCode":""}}] 
数据: {"error":3000,"errorMessage":"系统出错，正在排查","errorNo":3,"errorTip":"3000"}
=======================================================<

**Comment by xiaoke799** [comment]
10:50:29.250 [0.2.2-alpha]获取[我]主页成功17345288521821734490229250
10:50:52.873 [0.2.2-alpha]【青春特权】森林道具[双击卡]已领取 ✅
10:50:53.393 [0.2.2-alpha]【青春特权】森林道具[保护罩]已领取 ✅
10:50:53.855 [0.2.2-alpha]【青春特权】森林道具[加速器]已领取 ✅
10:51:38.719 [0.2.2-alpha]获取[我]主页成功17345288521821734490298719
10:52:04.828 [0.2.2-alpha]获取[我]主页成功17345288521821734490324828
10:55:37.758 [0.2.2-alpha]获取[我]主页成功17345288521821734490537758
10:56:11.480 [0.2.2-alpha]行走线路🚶🏻‍♂️[卡塔尔风情线]#前进了1257步

**Comment by xiaoke799** [comment]
10:50:23.154 [0.2.2-alpha][ApplicationHook]: hook matchVersion successfully 10:50:23.165 [0.2.2-alpha][ApplicationHook]: hook login successfully 10:50:23.167 [0.2.2-alpha][ApplicationHook]: hook service onCreate successfully 10:50:23.173 [0.2.2-alpha][ApplicationHook]: hook MiscUtils successfully 10:50:23.173 [0.2.2-alpha][ApplicationHook]: load success: com.eg.android.AlipayGphone 10:50:24.043 [0.2.2-alpha][ApplicationHook]: Service onCreate 10:50:24.062 [0.2.2-alpha][ApplicationHook]: hook registerBroadcastReceiver successfully 10:50:24.075 [0.2.2-alpha][Files]: [statistics]读:true;写:true 10:50:24.989 [0.2.2-alpha]模块版本：0.2.2-alpha 10:50:24.996 [0.2.2-alpha]开始加载 10:50:24.997 [0.2.2-alpha][Config]: 开始加载配置 10:50:25.030 [0.2.2-alpha]加载配置: 2088802325015989 10:50:25.315 [0.2.2-alpha][Config]: 格式化配置: 2088802325015989 10:50:25.325 [0.2.2-alpha][Config]: 加载配置结束 10:50:25.952 [0.2.2-alpha][NewRpcBridge]: 成功获取新的 RPC 调用方法 10:50:25.957 [0.2.2-alpha]取消定时唤醒:0|000000 10:50:25.963 [0.2.2-alpha]setAlarmTask triggerAtMillis:2024-12-19 00:00:00 operation:PendingIntent{1ffd045: android.os.BinderProxy@5bee39a} 10:50:25.964 [0.2.2-alpha]设置定时唤醒:0|000000 10:50:25.974 [0.2.2-alpha]setAlarmTask triggerAtMillis:1970-01-01 20:59:34 operation:PendingIntent{5bed525: android.os.BinderProxy@6d036fa} 10:50:25.975 [0.2.2-alpha]设置定时唤醒:1|2350 10:50:25.979 [0.2.2-alpha][ApplicationHook]: hook record request successfully 10:50:25.982 [0.2.2-alpha][ApplicationHook]: hook record response successfully 10:50:26.003 [0.2.2-alpha]执行开始-运动🏅 10:50:26.008 [0.2.2-alpha][AntSports]: hook readDailyStep successfully 10:50:26.009 [0.2.2-alpha]执行结束-运动🏅 10:50:26.090 [0.2.2-alpha][StatusUtil]: 重新格式化 status.json 10:50:26.129 [0.2.2-alpha][Files]: [statistics]读:true;写:true 10:50:26.175 [0.2.2-alpha]模块加载完成 🎉 10:50:26.199 [0.2.2-alpha][ApplicationHook]: 任务开始执行 10:50:28.093 [0.2.2-alpha]执行开始-蚂蚁森林🌳 10:50:29.233 [0.2.2-alpha]服务器时间：10:49:25，本地与服务器时间差：+1分钟 10:50:29.235 [0.2.2-alpha]进入[111]的蚂蚁森林 10:50:29.249 [0.2.2-alpha]用户[111]能量成熟时间: 19日05:51:53 10:50:29.250 [0.2.2-alpha]用户[111]能量成熟时间: 19日05:51:54 10:50:30.976 [0.2.2-alpha]sesame 查看广播:com.eg.android.AlipayGphone.sesame.execute intent:Intent { act=com.eg.android.AlipayGphone.sesame.execute flg=0x10 } 10:50:31.369 [0.2.2-alpha]服务器时间：10:49:27，本地与服务器时间差：+1分钟 10:50:31.370 [0.2.2-alpha]进入[---|]的蚂蚁森林 10:50:31.371 [0.2.2-alpha][----。|]被能量罩保护着哟 10:50:31.843 [0.2.2-alpha]服务器时间：10:49:27，本地与服务器时间差：+1分钟 10:50:31.844 [0.2.2-alpha]进入[ʕ•ᴥ•ʔ|]的蚂蚁森林 10:50:31.844 [0.2.2-alpha][ʕ•ᴥ•ʔ|]被能量罩保护着哟 10:50:32.525 [0.2.2-alpha]服务器时间：10:49:28，本地与服务器时间差：+1分钟 10:50:32.526 [0.2.2-alpha]进入[--|]的蚂蚁森林 10:50:32.526 [0.2.2-alpha][---|]被能量罩保护着哟 10:50:45.030 [0.2.2-alpha]服务器时间：10:49:40，本地与服务器时间差：+1分钟 10:50:45.031 [0.2.2-alpha]进入[---|]的蚂蚁森林 10:50:45.032 [0.2.2-alpha][---|]被能量罩保护着哟 10:50:45.956 [0.2.2-alpha]服务器时间：10:49:41，本地与服务器时间差：+1分钟 10:50:45.956 [0.2.2-alpha]进入[----]的蚂蚁森林 10:50:45.957 [0.2.2-alpha][----]被能量罩保护着哟 10:50:49.006 [0.2.2-alpha]🐼 已经有动物伙伴在巡护森林~ 10:50:54.190 [0.2.2-alpha]【青春特权-学生签到】：今日已签到 10:50:54.194 [0.2.2-alpha]执行结束-蚂蚁森林 10:50:54.196 [0.2.2-alpha][Files]: [statistics]读:true;写:true 10:50:54.955 [0.2.2-alpha]执行开始-蚂蚁庄园🏞 10:50:55.706 [0.2.2-alpha]执行开始-农场🌾 10:50:56.260 [0.2.2-alpha]领取道具[篱笆卡]#已满，暂不领取 10:50:56.456 [0.2.2-alpha]执行开始-海洋🌊 10:50:57.217 [0.2.2-alpha]农场今日已签到 10:50:57.220 [0.2.2-alpha]执行开始-神奇物种🐼 10:50:57.963 [0.2.2-alpha]庄园今日已签到 10:50:57.975 [0.2.2-alpha]开始执行古树🌳 10:50:57.995 [0.2.2-alpha]结束执行古树🌳 10:50:58.272 [0.2.2-alpha]当前参与人数过多，请稍后再试~ 10:50:58.282 [0.2.2-alpha]{"ariverRpcTraceId":"218300d717344901938582107e864e","resultCode":"SYSTEM_ERROR","resultDesc":"当前参与人数过多，请稍后再试~","resultMessage":"animalId is blank!","retryable":false,"success":false} 10:50:58.508 [0.2.2-alpha]神奇物种卡片今日收集完成！ 10:50:58.709 [0.2.2-alpha]执行开始-合种🌳 10:50:58.826 [0.2.2-alpha]执行结束-神奇物种🐼 10:50:59.185 [0.2.2-alpha]执行结束-合种🌳 10:50:59.436 [0.2.2-alpha]执行结束-农场🌾 10:50:59.459 [0.2.2-alpha]开始检测保护地 10:50:59.461 [0.2.2-alpha]开始执行-保护地🌏 10:50:59.671 [0.2.2-alpha]添加蹲点投喂🥣[----]在[18日11:20:18]执行 10:50:59.672 [0.2.2-alpha]还有待领取的饲料 10:50:59.951 [0.2.2-alpha]庄园今日已签到 10:50:59.977 [0.2.2-alpha]结束执行-保护地🌏 10:51:00.448 [0.2.2-alpha]运动签到今日已签到 10:51:00.538 [0.2.2-alpha]执行结束-海洋🌊 10:51:00.960 [0.2.2-alpha]执行开始-会员🏆 10:51:01.740 [0.2.2-alpha]执行开始-新村🏵 10:51:02.388 [0.2.2-alpha]添加蹲点请走⛪在[18日11:32:15]执行 10:51:02.389 [0.2.2-alpha]添加蹲点请走⛪在[18日11:10:48]执行 10:51:02.470 [0.2.2-alpha]执行开始-绿色经营🌱 10:51:03.647 [0.2.2-alpha][---|]的小鸡在挨饿 10:51:03.881 [0.2.2-alpha][AntMember]: queryAllStatusTaskList

**Comment by magisk317** [comment]
@xiaoke799 好像跟补丁方式无关，我是 lsp 也会无响应

**Comment by Fansirsqi** [comment]
目前明确了无响应是sleep太jb久缘故导致，删掉配置更模块
