### ISSUE TITLE
小米双开应用森林模块无法保存开启

### ISSUE THREAD

**Issue by huiwin** [Fansirsqi/Sesame-TK#7]
### 程序版本 / 框架版本 / 模块版本

10.5.88.800 or 1.9.3_mod7244

### 系统版本 / Android版本

澎湃OS

### 详细描述问题发生的具体原因

主应用配置之后可以正常使用、双开的已经回复旧版UI、设置后森林模块自动恢复、无法运行、下面的是log日志

### 提供模块问题 Log 或必要 Log

14:54:00.960 ERROR: java.lang.RuntimeException: java.lang.IllegalArgumentException: Cannot deserialize value of type `java.lang.Integer` from Boolean value (token `JsonToken.VALUE_FALSE`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at s2.g.e(JsonUtil.java:2)
	at c2.d.setObjectValue(ModelField.java:2)
	at io.github.lazyimmortal.sesame.data.ConfigV2.setModelFieldsMap(ConfigV2.java:12)
	at java.lang.reflect.Method.invoke(Native Method)
	at k1.o.deserializeAndSet(MethodProperty.java:9)
	at j1.c.deserialize(BeanDeserializer.java:25)
	at j1.m.readRootValue(DefaultDeserializationContext.java:4)
	at g1.y._bindAndClose(ObjectReader.java:7)
	at g1.y.readValue(ObjectReader.java:22)
	at io.github.lazyimmortal.sesame.data.ConfigV2.load(ConfigV2.java:10)
	at io.github.lazyimmortal.sesame.hook.ApplicationHook.a(ApplicationHook.java:21)
	at io.github.lazyimmortal.sesame.hook.ApplicationHook$b.afterHookedMethod(ApplicationHook.java:6)
	at f.qGNIawV.JZjLqC.l.X.T.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:294)
	at LSPHooker_.onResume(Unknown Source:8)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1614)
	at com.alipay.mobile.quinox.activity.QuinoxInstrumentation.callActivityOnResume(SourceFile:72)
	at android.app.Activity.performResume(Activity.java:9045)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5202)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5246)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2628)
	at com.alipay.stability.workaround.a.a.__handleMessage_stub_private(SourceFile:35)
	at com.alipay.stability.workaround.a.a.__handleMessage_stub(Unknown Source:29)
	at com.alipay.dexaop.perf.CallbackHandleMessageChain.proceed1(SourceFile:15)
	at com.alipay.dexaop.monitor.chain.interceptors.RunningObjectInterceptor.intercept1(Unknown Source:87)
	at com.alipay.dexaop.perf.CallbackHandleMessageChain.proceed1(SourceFile:30)
	at com.alipay.dexaop.DexAOPEntrySettings.android_os_Handler_Callback_handleMessage_proxy(SourceFile:13)
	at com.alipay.dexaop.DexAOPEntry.android_os_Handler_Callback_handleMessage_proxy(Unknown Source:0)
	at com.alipay.stability.workaround.a.a.handleMessage(Unknown Source:44)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
Caused by: java.lang.IllegalArgumentException: Cannot deserialize value of type `java.lang.Integer` from Boolean value (token `JsonToken.VALUE_FALSE`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at g1.w._convert(ObjectMapper.java:18)
	at g1.w.convertValue(ObjectMapper.java:3)
	at s2.g.e(JsonUtil.java:1)
	... 39 more
Caused by: m1.f: Cannot deserialize value of type `java.lang.Integer` from Boolean value (token `JsonToken.VALUE_FALSE`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at g1.h.reportInputMismatch(DeserializationContext.java:6)
	at g1.h.handleUnexpectedToken(DeserializationContext.java:16)
	at g1.h.handleUnexpectedToken(DeserializationContext.java:3)
	at l1.b0._parseInteger(StdDeserializer.java:2)
	at l1.v$i.deserialize(NumberDeserializers.java:6)
	at l1.v$i.deserialize(NumberDeserializers.java:1)
	at g1.w._convert(ObjectMapper.java:16)
	... 41 more

14:54:02.421 ERROR: AntFarm, java.lang.IllegalArgumentException: No enum constant io.github.lazyimmortal.sesame.model.task.antFarm.AntFarm.ToolType.DOLLTOOL
	at java.lang.Enum.valueOf(Enum.java:302)
	at io.github.lazyimmortal.sesame.model.task.antFarm.AntFarm$ToolType.valueOf(AntFarm.java:1)
	at io.github.lazyimmortal.sesame.model.task.antFarm.AntFarm.U(AntFarm.java:11)
	at io.github.lazyimmortal.sesame.model.task.antFarm.AntFarm.p(AntFarm.java:2)
	at f2.g$a.run(ModelTask.java:5)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

15:00:49.094 ERROR: java.lang.RuntimeException: java.lang.IllegalArgumentException: Cannot deserialize value of type `java.lang.Integer` from Boolean value (token `JsonToken.VALUE_FALSE`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at s2.g.e(JsonUtil.java:2)
	at c2.d.setObjectValue(ModelField.java:2)
	at io.github.lazyimmortal.sesame.data.ConfigV2.setModelFieldsMap(ConfigV2.java:12)
	at java.lang.reflect.Method.invoke(Native Method)
	at k1.o.deserializeAndSet(MethodProperty.java:9)
	at j1.c.deserialize(BeanDeserializer.java:25)
	at j1.m.readRootValue(DefaultDeserializationContext.java:4)
	at g1.y._bindAndClose(ObjectReader.java:7)
	at g1.y.readValue(ObjectReader.java:22)
	at io.github.lazyimmortal.sesame.data.ConfigV2.load(ConfigV2.java:10)
	at io.github.lazyimmortal.sesame.hook.ApplicationHook.a(ApplicationHook.java:21)
	at io.github.lazyimmortal.sesame.hook.ApplicationHook$e.onReceive(ApplicationHook.java:19)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1866)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
Caused by: java.lang.IllegalArgumentException: Cannot deserialize value of type `java.lang.Integer` from Boolean value (token `JsonToken.VALUE_FALSE`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at g1.w._convert(ObjectMapper.java:18)
	at g1.w.convertValue(ObjectMapper.java:3)
	at s2.g.e(JsonUtil.java:1)
	... 22 more
Caused by: m1.f: Cannot deserialize value of type `java.lang.Integer` from Boolean value (token `JsonToken.VALUE_FALSE`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at g1.h.reportInputMismatch(DeserializationContext.java:6)
	at g1.h.handleUnexpectedToken(DeserializationContext.java:16)
	at g1.h.handleUnexpectedToken(DeserializationContext.java:3)
	at l1.b0._parseInteger(StdDeserializer.java:2)
	at l1.v$i.deserialize(NumberDeserializers.java:6)
	at l1.v$i.deserialize(NumberDeserializers.java:1)
	at g1.w._convert(ObjectMapper.java:16)
	... 24 more

15:00:49.977 ERROR: AntFarm, java.lang.IllegalArgumentException: No enum constant io.github.lazyimmortal.sesame.model.task.antFarm.AntFarm.ToolType.DOLLTOOL
	at java.lang.Enum.valueOf(Enum.java:302)
	at io.github.lazyimmortal.sesame.model.task.antFarm.AntFarm$ToolType.valueOf(AntFarm.java:1)
	at io.github.lazyimmortal.sesame.model.task.antFarm.AntFarm.U(AntFarm.java:11)
	at io.github.lazyimmortal.sesame.model.task.antFarm.AntFarm.p(AntFarm.java:2)
	at f2.g$a.run(ModelTask.java:5)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by Fansirsqi** [comment]
你报告的应用错误应该不是本应用产生的
```
at io.github.lazyimmortal.sesame.data.ConfigV2.load(ConfigV2.java:10)
at io.github.lazyimmortal.sesame.hook.ApplicationHook.a(ApplicationHook.java:21)
at io.github.lazyimmortal.sesame.hook.ApplicationHook$e.onReceive(ApplicationHook.java:19)
```
从以上内容来看是另一个包产生的`lazyimmortal`
本包的配置与原版TK会有冲突，就是你装了别的TK，可能会和这个TK，可能会相互影响。。

**Comment by huiwin** [comment]
> 你报告的应用错误应该不是本应用产生的
> 
> ```
> at io.github.lazyimmortal.sesame.data.ConfigV2.load(ConfigV2.java:10)
> at io.github.lazyimmortal.sesame.hook.ApplicationHook.a(ApplicationHook.java:21)
> at io.github.lazyimmortal.sesame.hook.ApplicationHook$e.onReceive(ApplicationHook.java:19)
> ```
> 
> 从以上内容来看是另一个包产生的`lazyimmortal` 本包的配置与原版TK会有冲突，就是你装了别的TK，可能会和这个TK，可能会相互影响。。

另外一个应用我已经把模块禁用了、并且把存储的目录都删除了、这样还会冲突啊、按理说他两个使用的存储目录一样但是我把之前的记录都全部删除了应该没事的才对。

**Comment by loool-com** [comment]
> `lazyimmortal`

lazyimmortal 的版本配置格式变了，不向下兼容，你用的还是lazyimmortal 版本的配置，解析不了，把配件文件删了重新搞吧
